services:
  - type: web
    name: coffie-b
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon  # Choose your preferred region
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: coffie-b-db
          property: connectionString

databases:
  - name: coffie-b-db
    plan: free
    region: oregon  # Choose your preferred region