const DEFAULT_PROMPTS = [
    "My motivation to build a startup",
    "I'm passionate about",
    "In my free time, I",
    "My lifegoal is to",
    "The risk I'm most glad I took",
    "I geek out on",
    "I live by the motto",
    "My hacker moment",
    "A turning point in my life",
    "Believe it or not, I",
    "My favorite book(s)",
    "A valuable lesson I've Learned",
    "My strength / superpower",
    "My hustle story",
    "Words coworkers use to describe me",
    "My Working style",
    "One thing you should know about me",
    "My working style",
    "We'll get along if",
]